package za.co.habittracker
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import za.co.habittracker.data.*
import java.time.LocalDate
import java.time.format.TextStyle
import java.util.Locale
private val Ink=Color(0xFF101114);private val Panel=Color(0xFF1A1C20);private val Panel2=Color(0xFF25282D);private val Accent=Color(0xFFFFC83D);private val Blue=Color(0xFF6E8BFF);private val Green=Color(0xFF55D69E);private val Coral=Color(0xFFFF7474);private val Muted=Color(0xFF9A9DA6)
class MainActivity:ComponentActivity(){override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);setContent{HabitApp()}}}
@Composable fun HabitApp(vm:MainViewModel=viewModel()){var tab by remember{mutableIntStateOf(0)};MaterialTheme(colorScheme=darkColorScheme(background=Ink,surface=Panel,surfaceVariant=Panel2,primary=Accent,onPrimary=Ink)){Scaffold(containerColor=Ink,bottomBar={AppNav(tab){tab=it}},floatingActionButton={FloatingActionButton({tab=1},containerColor=Accent,contentColor=Ink,shape=CircleShape){Icon(Icons.Default.Add,"Add")}},floatingActionButtonPosition=FabPosition.Center){pad->Box(Modifier.padding(pad).fillMaxSize()){when(tab){0->Today(vm);1->Habits(vm);2->Tasks(vm);else->Insights(vm)}}}}}
@Composable private fun AppNav(selected:Int,onSelect:(Int)->Unit){NavigationBar(containerColor=Color(0xFF15171A)){listOf("Today" to Icons.Default.Home,"Habits" to Icons.Default.CheckCircle,"Tasks" to Icons.Default.Checklist,"Insights" to Icons.Default.BarChart).forEachIndexed{i,p->NavigationBarItem(selected=selected==i,onClick={onSelect(i)},icon={Icon(p.second,null)},label={Text(p.first)},colors=NavigationBarItemDefaults.colors(selectedIconColor=Accent,selectedTextColor=Accent,indicatorColor=Panel2,unselectedIconColor=Muted,unselectedTextColor=Muted))}}}
@Composable private fun Header(title:String,subtitle:String){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(subtitle,color=Muted)};IconButton({}){Icon(Icons.Default.Settings,null,tint=Muted)}}}
@Composable private fun DateStrip(){val today=LocalDate.now();Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){(-3..3).forEach{o->val d=today.plusDays(o.toLong());val active=o==0;Column(Modifier.width(42.dp).clip(RoundedCornerShape(18.dp)).background(if(active)Accent else Color.Transparent).padding(vertical=9.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(d.dayOfWeek.getDisplayName(TextStyle.SHORT,Locale.getDefault()).take(1),color=if(active)Ink else Muted,style=MaterialTheme.typography.labelSmall);Text(d.dayOfMonth.toString(),color=if(active)Ink else Color.White,fontWeight=FontWeight.Bold)}}}}
@Composable fun Today(vm:MainViewModel){val habits by vm.habits.collectAsState();val comp by vm.completions.collectAsState();val tasks by vm.tasks.collectAsState();val today=LocalDate.now().toString();LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(18.dp)){item{Header("Today",LocalDate.now().month.getDisplayName(TextStyle.FULL,Locale.getDefault())+" "+LocalDate.now().dayOfMonth)};item{DateStrip()};item{val done=comp.count{it.day==today};Summary(done,habits.size,tasks.count{!it.completed})};item{Section("Your habits",habits.size)};items(habits){HabitCard(it,comp,vm)};if(habits.isEmpty())item{EmptyCard()};item{Section("Up next",tasks.count{!it.completed})};items(tasks.filter{!it.completed}.take(4)){TaskCard(it,vm)}}}
@Composable private fun Summary(done:Int,total:Int,tasks:Int){val p=if(total==0)0f else done.toFloat()/total;Card(colors=CardDefaults.cardColors(containerColor=Panel),shape=RoundedCornerShape(26.dp)){Row(Modifier.padding(20.dp).fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("DAILY PROGRESS",color=Muted,style=MaterialTheme.typography.labelMedium);Text("${(p*100).toInt()}%",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Bold);Text("$done of $total habits · $tasks tasks left",color=Muted)};Box(Modifier.size(72.dp),contentAlignment=Alignment.Center){CircularProgressIndicator(progress={p},Modifier.fillMaxSize(),color=Accent,trackColor=Panel2,strokeWidth=7.dp);Text("$done/$total",fontWeight=FontWeight.Bold)}}}}
@Composable private fun Section(title:String,count:Int){Row(verticalAlignment=Alignment.CenterVertically){Text(title,Modifier.weight(1f),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text(count.toString(),color=Muted)}}
@Composable private fun HabitCard(h:Habit,comp:List<HabitCompletion>,vm:MainViewModel){val today=LocalDate.now().toString();val checked=comp.any{it.habitId==h.id&&it.day==today};val palette=listOf(Accent,Blue,Green,Coral);val color=palette[kotlin.math.abs(h.title.hashCode())%palette.size];Card(colors=CardDefaults.cardColors(containerColor=Panel),shape=RoundedCornerShape(24.dp)){Column(Modifier.clickable{vm.toggleHabit(h.id,checked)}.padding(18.dp)){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(42.dp).background(color.copy(alpha=.16f),CircleShape),contentAlignment=Alignment.Center){Icon(if(checked)Icons.Default.Check else Icons.Default.Bolt,null,tint=color)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(h.title,fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium);Text("🔥 ${vm.streak(h.id,comp)} day streak",color=Muted,style=MaterialTheme.typography.bodySmall)};Checkbox(checked,{vm.toggleHabit(h.id,checked)},colors=CheckboxDefaults.colors(checkedColor=color))};Spacer(Modifier.height(16.dp));WeekDots(h.id,comp,color)}}}
@Composable private fun WeekDots(id:String,comp:List<HabitCompletion>,color:Color){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){(6 downTo 0).forEach{n->val d=LocalDate.now().minusDays(n.toLong());val on=comp.any{it.habitId==id&&it.day==d.toString()};Column(horizontalAlignment=Alignment.CenterHorizontally){Text(d.dayOfWeek.getDisplayName(TextStyle.SHORT,Locale.getDefault()).take(1),color=Muted,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(6.dp));Box(Modifier.size(32.dp).background(if(on)color else Panel2,CircleShape),contentAlignment=Alignment.Center){Text(d.dayOfMonth.toString(),color=if(on)Ink else Muted,style=MaterialTheme.typography.labelMedium,fontWeight=FontWeight.Bold)}}}}}
@Composable fun Habits(vm:MainViewModel){val habits by vm.habits.collectAsState();val comp by vm.completions.collectAsState();var title by remember{mutableStateOf("")};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Header("Habits","Build consistency, one day at a time")};item{OutlinedTextField(title,{title=it},Modifier.fillMaxWidth(),placeholder={Text("Add a new habit")},trailingIcon={IconButton({vm.addHabit(title);title=""}){Icon(Icons.Default.Add,null)}},singleLine=true,shape=RoundedCornerShape(20.dp))};items(habits){HabitCard(it,comp,vm)}}}
@Composable fun Tasks(vm:MainViewModel){val tasks by vm.tasks.collectAsState();var q by remember{mutableStateOf("")};var title by remember{mutableStateOf("")};var status by remember{mutableIntStateOf(0)};val shown=tasks.filter{(q.isBlank()||it.title.contains(q,true)||it.tags.contains(q,true))&&(status==0||(status==1&&!it.completed)||(status==2&&it.completed))};LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Header("Tasks","Plan what matters")};item{OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),leadingIcon={Icon(Icons.Default.Search,null)},placeholder={Text("Search tasks and tags")},singleLine=true,shape=RoundedCornerShape(20.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){listOf("All","Open","Done").forEachIndexed{i,s->FilterChip(selected=status==i,onClick={status=i},label={Text(s)})}}};item{Row(verticalAlignment=Alignment.CenterVertically){OutlinedTextField(title,{title=it},Modifier.weight(1f),placeholder={Text("New task")},singleLine=true,shape=RoundedCornerShape(18.dp));Spacer(Modifier.width(8.dp));FilledIconButton({vm.addTask(title);title=""},colors=IconButtonDefaults.filledIconButtonColors(containerColor=Accent,contentColor=Ink)){Icon(Icons.Default.Add,null)}}};items(shown){TaskCard(it,vm)}}}
@Composable private fun TaskCard(t:Task,vm:MainViewModel){val priority=listOf("Low","Medium","High","Urgent").getOrElse(t.priority){"Medium"};val color=when(t.priority){2->Coral;3->Color(0xFFFF5252);else->Blue};Card(colors=CardDefaults.cardColors(containerColor=Panel),shape=RoundedCornerShape(20.dp)){Row(Modifier.fillMaxWidth().padding(14.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(t.completed,{vm.toggleTask(t)});Spacer(Modifier.width(6.dp));Column(Modifier.weight(1f)){Text(t.title,fontWeight=FontWeight.SemiBold);if(t.tags.isNotBlank())Text(t.tags,color=Muted,style=MaterialTheme.typography.bodySmall)};Surface(color=color.copy(alpha=.15f),shape=RoundedCornerShape(10.dp)){Text(priority,Modifier.padding(horizontal=9.dp,vertical=5.dp),color=color,style=MaterialTheme.typography.labelSmall)}}}}
@Composable fun Insights(vm:MainViewModel){val habits by vm.habits.collectAsState();val comp by vm.completions.collectAsState();LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{Header("Insights","Your consistency at a glance")};item{Heatmap(comp)};items(habits){h->val count=(0..29).count{n->comp.any{it.habitId==h.id&&it.day==LocalDate.now().minusDays(n.toLong()).toString()}};Card(colors=CardDefaults.cardColors(containerColor=Panel),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(18.dp)){Row{Text(h.title,Modifier.weight(1f),fontWeight=FontWeight.Bold);Text("$count / 30",color=Accent)};Spacer(Modifier.height(12.dp));LinearProgressIndicator(progress={count/30f},Modifier.fillMaxWidth().height(8.dp).clip(CircleShape),color=Accent,trackColor=Panel2);Spacer(Modifier.height(10.dp));Text("Current streak  ${vm.streak(h.id,comp)} days",color=Muted)}}}}}
@Composable private fun Heatmap(comp:List<HabitCompletion>){Card(colors=CardDefaults.cardColors(containerColor=Panel),shape=RoundedCornerShape(24.dp)){Column(Modifier.padding(18.dp)){Text("Activity",fontWeight=FontWeight.Bold,style=MaterialTheme.typography.titleMedium);Text("Last 12 weeks",color=Muted);Spacer(Modifier.height(16.dp));Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){(11 downTo 0).forEach{w->Column(verticalArrangement=Arrangement.spacedBy(4.dp)){(6 downTo 0).forEach{d->val date=LocalDate.now().minusDays((w*7+d).toLong());val n=comp.count{it.day==date.toString()};Box(Modifier.size(14.dp).background(if(n>0)Accent.copy(alpha=(.35f+n*.18f).coerceAtMost(1f)) else Panel2,RoundedCornerShape(3.dp)))}}}}}}}}
@Composable private fun EmptyCard(){Card(colors=CardDefaults.cardColors(containerColor=Panel),shape=RoundedCornerShape(22.dp)){Column(Modifier.padding(22.dp)){Text("No habits yet",fontWeight=FontWeight.Bold);Text("Create your first habit with the + button.",color=Muted)}}}}
